version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: yellow_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yellow_db
    ports:
      - "5431:5432"
    networks:
      - yellow
networks:
  yellow: